language: ruby
sudo: false
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
env:
  -
  - ACTIVE_RECORD_VERSION=4.0.0
  - ACTIVE_RECORD_VERSION=4.1.0
  - ACTIVE_RECORD_VERSION=4.2.0
  - ACTIVE_RECORD_VERSION=5.0.0
matrix:
  allow_failures:
    - rvm: 2.4
      env: ACTIVE_RECORD_VERSION=4.0.0
    - rvm: 2.4
      env: ACTIVE_RECORD_VERSION=4.1.0
    - rvm: 2.5
      env: ACTIVE_RECORD_VERSION=4.0.0
    - rvm: 2.5
      env: ACTIVE_RECORD_VERSION=4.1.0
    - rvm: 2.6
      env: ACTIVE_RECORD_VERSION=4.0.0
    - rvm: 2.6
      env: ACTIVE_RECORD_VERSION=4.1.0
before_install:
  - gem update --system
  - gem --version
install:
  # Bundler v2 only supports Ruby v2.3 and above
  # For Ruby v2.2, install Bundler v1.x
  - if [ $TRAVIS_RUBY_VERSION == "2.2" ];
    then gem install bundler -v '< 2';
    else gem install bundler;
    fi
  - bundle --version
  - bundle install --jobs=3 --retry=3
script:
  - 'bundle exec rake'
notifications:
  email: false
