name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.7.5", "3.0.3", "3.1.0", "3.2.0"]
        active_record_version: ["6.0", "6.1", "7.0"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.131.0
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Install dependencies
        env:
          ACTIVE_RECORD_VERSION: ${{ matrix.active_record_version }}
        run: bundle install --jobs 3 --retry 3
      - name: Run tests
        env:
          CI: '1'
        run: bundle exec rspec
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.ruby_version }}-${{ matrix.active_record_version }}
          parallel: true
  finish:
    needs: test
    runs-on: ubuntu-20.04
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true

