name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby_version: [2.7, 3.0, 3.1, 3.2]
        active_record_version: [6.0, 6.1, 7.0]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Install dependencies
        env:
          ACTIVE_RECORD_VERSION: ${{ matrix.active_record_version }}
        run: bundle install --jobs 3 --retry 3
      - name: Run tests
        run: bundle exec rake

